title: Box plot- Histograms-QQ PLOT-violin plot
description: 'Basic commands with R for plotting '
template:
  repo: box-plot-histograms-qq-plot-violin-plot-template
  name: box-plot-histograms-qq-plot-violin-plot
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
